# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provider "virtualbox"
  
  config.vm.box = "mybionic"
  config.vm.box_check_update = false

  config.vm.synced_folder ".", "/vagrant", disabled: false

  # VirtualBox
  config.vm.provider "virtualbox" do |v|
    v.gui = true
    v.memory = 4096
    v.cpus = 4
    v.name = "bionic"

    v.customize ["setextradata", "global", "GUI/MaxGuestResolution", "any"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
    v.customize ["modifyvm", :id, "--rtcuseutc", "on"]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
  end

end
